baseURL: 
languageCode: en-us
defaultContentLanguage: it
title: Bluto Blog
theme: cupper-hugo-theme
#googleAnalytics: UA-123456789-1
disqusShortname: bluto
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Un blog di miglioramento continuo, flusso di coscienza e riflessioni.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  navTitleText: Bluto Blog
  logoAlt: Bluto Blog
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  utterances:
    repo: cloud-03/blutoBlog
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Università
      url: /universita/
      weight: 3
    - name: Films & Books
      url: /film/
      weight: 5
    - name: Politics
      url: /politics/
      weight: 6  
    - name: About
      url: /about/
      weight: 7

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
