[build]
  publish = "blutoBlog/public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://prova.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
